# Generated by Django 4.0.4 on 2022-05-07 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('metros', models.IntegerField()),
                ('ambientes', models.CharField(max_length=50)),
                ('antiguedad', models.CharField(max_length=50)),
                ('ubicación', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('metros', models.IntegerField()),
                ('ambientes', models.CharField(max_length=50)),
                ('antiguedad', models.CharField(max_length=50)),
                ('ubicación', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('metros', models.IntegerField()),
                ('ambientes', models.CharField(max_length=50)),
                ('antiguedad', models.CharField(max_length=50)),
                ('ubicación', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('metros', models.IntegerField()),
                ('ambientes', models.CharField(max_length=50)),
                ('antiguedad', models.CharField(max_length=50)),
                ('ubicación', models.CharField(max_length=50)),
            ],
        ),
    ]
