# Generated by Django 4.0.4 on 2022-05-07 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppInmo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BLog',
        ),
    ]
